require 'hoe'
require './lib/football-timezones/version.rb'

Hoe.spec 'football-timezones' do

  self.version = SportDb::Module::Timezones::VERSION

  self.summary = "football-timezones - time & timezone helpers for football (league) data"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email  = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['tzinfo'],
    ['season-formats'],
    ['cocos'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 3.1.0'
  }

end
