require 'hoe'
require './lib/sportdb/structs/version.rb'

Hoe.spec 'sportdb-structs' do

  self.version = SportDb::Module::Structs::VERSION

  self.summary = "sportdb-structs - sport data structures for matches, scores, leagues, seasons, rounds, groups, teams, clubs and more"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email  = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['alphabets',      '>= 1.0.0'],
    ['date-formats',   '>= 1.0.2'],
    ['score-formats',  '>= 0.1.1'],
    ['season-formats', '>= 0.0.1'],
    ['csvreader',      '>= 1.2.4'],
    ['sportdb-langs',  '>= 0.1.1'],
  ]

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }
end
