require 'hoe'
require './lib/sportdb/readers/version.rb'

Hoe.spec 'sportdb-readers' do

  self.version = SportDb::Readers::VERSION

  self.summary = "sportdb-readers - sport.db readers for leagues, seasons, clubs, match schedules and results, and more"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['sportdb-sync',    '>= 1.2.0'],
  ]

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
