require 'hoe'
require './lib/footballdb-data.rb'

Hoe.spec 'footballdb-data' do

  self.version = FootballDb::Data::VERSION

  self.summary = "footballdb-data - built-in (default) football data incl. leagues & cups, clubs, grounds, and more"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = []

  self.spec_extras = {
    required_ruby_version: '>= 3.1.0'
  }
end
