require 'hoe'
require './lib/sportdb/keys/version.rb'

Hoe.spec 'sportdb-keys' do

  self.version = SportDb::Keys::VERSION

  self.summary = 'sportdb-keys - sport.db addon for well known keys (e.g. EURO, EN, etc.) and model finder shortcuts, etc.'
  self.description = summary

  self.urls = ['https://github.com/sportdb/sport.db.keys.ruby']

  self.author = 'Gerald Bauer'
  self.email = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.spec_extras = {
   :required_ruby_version => '>= 1.9.2'
  }

end
