#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'
class RaccMatchParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
   103,    54,    60,   120,    28,    58,    35,    92,    23,   128,
    80,    60,    81,    60,    43,   121,    41,    39,    38,    52,
    55,    61,    62,    65,    65,    31,    55,    12,   127,    30,
    61,    28,    61,    62,    40,    16,    12,    50,    30,    13,
    28,    25,    14,    15,    16,    21,    23,    54,    13,    37,
    25,    14,    15,    43,    21,    23,    72,    74,    75,    76,
    36,    44,    47,    46,    68,    52,    55,    85,    86,   105,
   106,   118,   119,   129,   130,   137,   130,    56,    66,    70,
    71,    83,    87,    88,    65,    89,    91,    94,    96,    99,
    40,   100,   101,    43,   108,    43,   110,    35,   112,   113,
    80,    65,   122,   123,   124,    99,   126,   132,    65,    43,
    43,    35,   135,    65,   138,    99,   140,   141 ]

racc_action_check = [
    63,    19,    25,    82,    16,    21,    12,    52,    21,    95,
    35,    99,    35,    50,    16,    82,    16,    15,    14,    19,
    19,    25,    25,    63,    25,     1,    52,     1,    95,     1,
    99,     1,    50,    50,    15,     1,     0,    18,     0,     1,
     0,     1,     1,     1,     0,     1,     1,    48,     0,    13,
     0,     0,     0,    27,     0,     0,    33,    33,    33,    33,
    13,    17,    17,    17,    27,    48,    48,    38,    38,    65,
    65,    81,    81,    97,    97,   125,   125,    20,    26,    28,
    31,    36,    41,    42,    43,    45,    49,    53,    55,    56,
    58,    59,    62,    67,    68,    70,    72,    73,    75,    76,
    78,    80,    84,    87,    88,    91,    93,   100,   103,   107,
   109,   115,   116,   117,   128,   130,   131,   134 ]

racc_action_pointer = [
    34,    25,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    -1,    45,     3,    13,    -2,    57,    21,    -3,
    72,   -13,   nil,   nil,   nil,    -4,    74,    37,    52,   nil,
   nil,    80,   nil,    53,   nil,     2,    65,   nil,    49,   nil,
   nil,    71,    72,    56,   nil,    68,   nil,   nil,    43,    81,
     7,   nil,     3,    83,   nil,    72,    73,   nil,    69,    75,
   nil,   nil,    76,    -5,   nil,    40,   nil,    77,    90,   nil,
    79,   nil,    92,    90,   nil,    94,    95,   nil,    92,   nil,
    73,    59,    -1,   nil,    98,   nil,   nil,    99,   100,   nil,
   nil,    89,   nil,   102,   nil,     4,   nil,    69,   nil,     5,
    81,   nil,   nil,    80,   nil,   nil,   nil,    93,   nil,    94,
   nil,   nil,   nil,   nil,   nil,   104,   101,    85,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    71,   nil,   nil,    98,   nil,
    99,   100,   nil,   nil,   108,   nil,   nil,   nil,   nil,   nil,
   nil,   nil ]

racc_action_default = [
   -90,   -90,    -1,    -3,    -4,    -5,    -6,    -7,    -8,    -9,
   -10,   -11,   -90,   -90,   -41,   -54,   -90,   -90,   -90,   -90,
   -66,   -51,   -53,   -56,   -65,   -90,   -90,   -74,   -90,   -79,
   -89,   -90,    -2,   -90,   -13,   -20,   -90,   -39,   -90,   -37,
   -55,   -90,   -90,   -90,   -40,   -90,   -43,   -44,   -90,   -66,
   -90,   -46,   -90,   -90,   -60,   -90,   -90,   -52,   -54,   -90,
   -68,   -69,   -90,   -81,   -82,   -85,   -73,   -90,   -77,   -80,
   -90,   142,   -90,   -90,   -15,   -16,   -18,   -21,   -22,   -24,
   -90,   -90,   -90,   -32,   -90,   -35,   -36,   -90,   -90,   -42,
   -45,   -90,   -57,   -90,   -59,   -61,   -63,   -90,   -49,   -90,
   -67,   -70,   -83,   -90,   -86,   -87,   -88,   -76,   -78,   -75,
   -12,   -14,   -17,   -19,   -23,   -90,   -90,   -27,   -29,   -30,
   -31,   -33,   -34,   -38,   -72,   -90,   -58,   -62,   -90,   -48,
   -90,   -90,   -71,   -84,   -90,   -26,   -28,   -47,   -64,   -50,
   -67,   -25 ]

racc_goto_table = [
    49,    34,    69,   102,    79,    97,    51,   107,     2,    32,
   109,     1,    33,    73,    77,    78,   116,   117,    82,    84,
   115,    45,    48,    57,    93,    95,   131,    42,    67,   104,
   nil,   nil,   nil,   nil,   nil,    90,   nil,   nil,    98,   nil,
   125,   nil,   nil,   133,   nil,   nil,   nil,   114,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   136,   nil,   nil,
   nil,   nil,   111,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    98,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    69,   nil,    69,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   134,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   139 ]

racc_goto_check = [
    28,    13,    38,    18,    17,    29,    27,    36,     2,     2,
    36,     1,    12,    14,    15,    16,    19,    20,    21,    22,
    18,    24,    26,    30,    31,    32,    34,    35,    37,    40,
   nil,   nil,   nil,   nil,   nil,    27,   nil,   nil,    28,   nil,
    29,   nil,   nil,    18,   nil,   nil,   nil,    17,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    18,   nil,   nil,
   nil,   nil,    13,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    28,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    38,   nil,    38,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    13,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    28 ]

racc_goto_pointer = [
   nil,    11,     8,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     0,   -11,   -20,   -21,   -20,   -31,   -60,   -65,
   -64,   -18,   -19,   nil,     4,   nil,     4,   -13,   -18,   -51,
     2,   -28,   -30,   nil,   -73,    11,   -60,     1,   -25,   nil,
   -36 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,     6,     7,     8,     9,
    10,    11,   nil,   nil,   nil,   nil,   nil,   nil,    64,   nil,
   nil,   nil,   nil,    17,   nil,    18,    19,   nil,    20,   nil,
    22,    53,   nil,    24,    59,    26,    27,   nil,    29,    63,
   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 32, :_reduce_none,
  2, 32, :_reduce_none,
  1, 33, :_reduce_none,
  1, 33, :_reduce_none,
  1, 33, :_reduce_none,
  1, 33, :_reduce_none,
  1, 33, :_reduce_none,
  1, 33, :_reduce_none,
  1, 33, :_reduce_none,
  1, 33, :_reduce_none,
  1, 33, :_reduce_none,
  4, 42, :_reduce_12,
  1, 43, :_reduce_13,
  3, 43, :_reduce_14,
  2, 43, :_reduce_15,
  1, 45, :_reduce_none,
  2, 45, :_reduce_17,
  1, 45, :_reduce_none,
  2, 45, :_reduce_19,
  1, 44, :_reduce_20,
  2, 44, :_reduce_21,
  1, 46, :_reduce_22,
  2, 46, :_reduce_23,
  1, 46, :_reduce_24,
  4, 48, :_reduce_25,
  3, 47, :_reduce_26,
  1, 50, :_reduce_27,
  2, 50, :_reduce_28,
  1, 51, :_reduce_none,
  1, 51, :_reduce_none,
  4, 37, :_reduce_31,
  1, 52, :_reduce_32,
  2, 52, :_reduce_33,
  4, 38, :_reduce_34,
  1, 53, :_reduce_35,
  1, 53, :_reduce_36,
  2, 34, :_reduce_37,
  4, 34, :_reduce_38,
  2, 35, :_reduce_39,
  2, 36, :_reduce_40,
  1, 54, :_reduce_41,
  3, 54, :_reduce_42,
  1, 55, :_reduce_none,
  1, 55, :_reduce_none,
  3, 39, :_reduce_45,
  2, 39, :_reduce_46,
  5, 39, :_reduce_47,
  4, 39, :_reduce_48,
  1, 60, :_reduce_49,
  3, 60, :_reduce_50,
  1, 56, :_reduce_51,
  2, 56, :_reduce_52,
  1, 56, :_reduce_none,
  1, 61, :_reduce_54,
  2, 61, :_reduce_55,
  1, 61, :_reduce_56,
  2, 58, :_reduce_57,
  3, 58, :_reduce_58,
  2, 58, :_reduce_59,
  1, 58, :_reduce_60,
  2, 62, :_reduce_61,
  3, 62, :_reduce_62,
  1, 63, :_reduce_63,
  3, 63, :_reduce_64,
  1, 57, :_reduce_none,
  1, 57, :_reduce_none,
  3, 59, :_reduce_67,
  1, 65, :_reduce_none,
  1, 65, :_reduce_none,
  3, 64, :_reduce_70,
  4, 64, :_reduce_71,
  4, 40, :_reduce_72,
  2, 40, :_reduce_73,
  1, 66, :_reduce_74,
  3, 66, :_reduce_75,
  3, 66, :_reduce_76,
  1, 68, :_reduce_none,
  2, 68, :_reduce_none,
  1, 67, :_reduce_79,
  2, 67, :_reduce_80,
  2, 69, :_reduce_81,
  1, 70, :_reduce_82,
  2, 70, :_reduce_83,
  3, 70, :_reduce_84,
  1, 49, :_reduce_85,
  2, 49, :_reduce_86,
  1, 71, :_reduce_87,
  1, 71, :_reduce_88,
  1, 41, :_reduce_89 ]

racc_reduce_n = 90

racc_shift_n = 142

racc_token_table = {
  false => 0,
  :error => 1,
  :PROP => 2,
  "." => 3,
  :NEWLINE => 4,
  "," => 5,
  "-" => 6,
  :PROP_NAME => 7,
  "(" => 8,
  ")" => 9,
  "[" => 10,
  "]" => 11,
  :YELLOW_CARD => 12,
  :RED_CARD => 13,
  :GROUP => 14,
  "|" => 15,
  :TEXT => 16,
  :ROUND => 17,
  :DATE => 18,
  :DURATION => 19,
  :ORD => 20,
  :TIME => 21,
  :STATUS => 22,
  "@" => 23,
  :TIMEZONE => 24,
  :VS => 25,
  :SCORE => 26,
  ";" => 27,
  :MINUTE => 28,
  :OG => 29,
  :PEN => 30 }

racc_nt_base = 31

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "PROP",
  "\".\"",
  "NEWLINE",
  "\",\"",
  "\"-\"",
  "PROP_NAME",
  "\"(\"",
  "\")\"",
  "\"[\"",
  "\"]\"",
  "YELLOW_CARD",
  "RED_CARD",
  "GROUP",
  "\"|\"",
  "TEXT",
  "ROUND",
  "DATE",
  "DURATION",
  "ORD",
  "TIME",
  "STATUS",
  "\"@\"",
  "TIMEZONE",
  "VS",
  "SCORE",
  "\";\"",
  "MINUTE",
  "OG",
  "PEN",
  "$start",
  "statements",
  "statement",
  "date_header",
  "group_header",
  "round_header",
  "group_def",
  "round_def",
  "match_line",
  "goal_lines",
  "empty_line",
  "lineup_lines",
  "lineup",
  "lineup_name",
  "lineup_sep",
  "lineup_name_more",
  "card",
  "lineup_sub",
  "minute",
  "card_body",
  "card_type",
  "team_values",
  "round_date_opts",
  "round_values",
  "round_sep",
  "match_opts",
  "match",
  "more_match_opts",
  "match_fixture",
  "more_match_fixtures",
  "date_opts",
  "geo_opts",
  "geo_values",
  "match_result",
  "match_sep",
  "goal_lines_body",
  "goals",
  "goal_sep",
  "goal",
  "minutes",
  "minute_opts" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

module_eval(<<'.,.,', 'parser.y', 30)
  def _reduce_12(val, _values, result)
      @tree << LineupLine.new( team:    val[0],
                                                    lineup:  val[1]
                                                  ) 

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 37)
  def _reduce_13(val, _values, result)
     result = [[val[0]]]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 40)
  def _reduce_14(val, _values, result)
                           ## if lineup_sep is -  start a new sub array!!
                       if val[1] == '-'
                          result << [val[2]]
                       else
                          result[-1] << val[2]
                       end

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 48)
  def _reduce_15(val, _values, result)
     result = val[0]
    result
  end
.,.,

# reduce 16 omitted

module_eval(<<'.,.,', 'parser.y', 52)
  def _reduce_17(val, _values, result)
     result = val[0]
    result
  end
.,.,

# reduce 18 omitted

module_eval(<<'.,.,', 'parser.y', 54)
  def _reduce_19(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 60)
  def _reduce_20(val, _values, result)
                                  result = Lineup.new( name: val[0] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 64)
  def _reduce_21(val, _values, result)
                                  kwargs = { name: val[0] }.merge( val[1] )
                              result = Lineup.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 70)
  def _reduce_22(val, _values, result)
                                  result = { card: val[0] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 74)
  def _reduce_23(val, _values, result)
                                  result = { card: val[0], sub: val[1] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 78)
  def _reduce_24(val, _values, result)
                                  result = { sub: val[0] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 84)
  def _reduce_25(val, _values, result)
                                  result = Sub.new( minute: val[1], sub: val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 90)
  def _reduce_26(val, _values, result)
                                  kwargs = val[1]
                              result = Card.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 95)
  def _reduce_27(val, _values, result)
     result = { name: val[0] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 98)
  def _reduce_28(val, _values, result)
     result = { name: val[0], minute: val[1] }
    result
  end
.,.,

# reduce 29 omitted

# reduce 30 omitted

module_eval(<<'.,.,', 'parser.y', 109)
  def _reduce_31(val, _values, result)
                          @tree << GroupDef.new( name:  val[0],
                                             teams: val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 115)
  def _reduce_32(val, _values, result)
                                                   result = val
                                               ## e.g. val is ["Austria"] 

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 119)
  def _reduce_33(val, _values, result)
                                                   result.push( val[1] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 128)
  def _reduce_34(val, _values, result)
                          kwargs = { name: val[0] }.merge( val[2] )
                      @tree<< RoundDef.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 133)
  def _reduce_35(val, _values, result)
     result = { date: val[0][1] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 134)
  def _reduce_36(val, _values, result)
     result = { duration: val[0][1] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 140)
  def _reduce_37(val, _values, result)
                         @tree <<  DateHeader.new( date: val[0][1] )  

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 144)
  def _reduce_38(val, _values, result)
                         @tree <<  DateHeader.new( date: val[1][1] )  

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 151)
  def _reduce_39(val, _values, result)
                         @tree <<  GroupHeader.new( name: val[0] )  

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 161)
  def _reduce_40(val, _values, result)
                         @tree <<  RoundHeader.new( names: val[0] )  

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 164)
  def _reduce_41(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 165)
  def _reduce_42(val, _values, result)
       result.push( val[2] )
    result
  end
.,.,

# reduce 43 omitted

# reduce 44 omitted

module_eval(<<'.,.,', 'parser.y', 176)
  def _reduce_45(val, _values, result)
                           kwargs = {}.merge( val[0], val[1], val[2] )
                       @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 181)
  def _reduce_46(val, _values, result)
                          kwargs = {}.merge( val[0], val[1] )
                      @tree << MatchLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 189)
  def _reduce_47(val, _values, result)
                          kwargs = {}.merge( val[0], val[1] )
                      @tree << MatchLine.new( **kwargs )
                     
                      ## add more match fixtures
                      val[3].each do |kwargs|
                         @tree << MatchLine.new( **kwargs)
                      end

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 199)
  def _reduce_48(val, _values, result)
                          kwargs = val[0]
                      @tree << MatchLine.new( **kwargs )
 
                      ## add more match fixtures
                      val[2].each do |kwargs|
                         @tree << MatchLine.new( **kwargs)
                      end

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 213)
  def _reduce_49(val, _values, result)
                                        puts "  REDUCE => more_match_fixtures : match_fixture" 
                                    result = val

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 218)
  def _reduce_50(val, _values, result)
                                         puts "  REDUCE => more_match_fixtures : more_match_fixtures ',' match_fixture " 
                                     result.push( val[2] )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 224)
  def _reduce_51(val, _values, result)
       result = { ord: val[0][1][:value] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 225)
  def _reduce_52(val, _values, result)
       result = { ord: val[0][1][:value] }.merge( val[1] )
    result
  end
.,.,

# reduce 53 omitted

module_eval(<<'.,.,', 'parser.y', 229)
  def _reduce_54(val, _values, result)
       result = { date: val[0][1]}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 230)
  def _reduce_55(val, _values, result)
       result = { date: val[0][1], time: val[1][1] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 231)
  def _reduce_56(val, _values, result)
       result = { time: val[0][1]}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 237)
  def _reduce_57(val, _values, result)
                          ## todo - add possible status_notes too!!! 
                      result = { status: val[0][1][:status] }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 242)
  def _reduce_58(val, _values, result)
                         result = { status: val[0][1][:status] }.merge( val[1] ) 

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 244)
  def _reduce_59(val, _values, result)
     result = {}.merge( val[0] )
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 245)
  def _reduce_60(val, _values, result)
     result = {}
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 251)
  def _reduce_61(val, _values, result)
     result = { geo: val[1] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 252)
  def _reduce_62(val, _values, result)
     result = { geo: val[1], timezone: val[2] }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 255)
  def _reduce_63(val, _values, result)
      result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 256)
  def _reduce_64(val, _values, result)
      result.push( val[2] )
    result
  end
.,.,

# reduce 65 omitted

# reduce 66 omitted

module_eval(<<'.,.,', 'parser.y', 264)
  def _reduce_67(val, _values, result)
                                   puts "  match MATCH_FIXTURE"
                               result = { team1: val[0],
                                          team2: val[2] }   

    result
  end
.,.,

# reduce 68 omitted

# reduce 69 omitted

module_eval(<<'.,.,', 'parser.y', 275)
  def _reduce_70(val, _values, result)
                             puts "  match TEXT  SCORE  TEXT"
                         result = { team1: val[0],
                                    team2: val[2],
                                    score: val[1][1]
                                  }   

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 289)
  def _reduce_71(val, _values, result)
                             puts "  match TEXT match_sep TEXT SCORE"
                         result = { team1: val[0], 
                                    team2: val[2],
                                    score: val[3][1] 
                                  }

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 311)
  def _reduce_72(val, _values, result)
                           kwargs = val[1]
                       @tree << GoalLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 316)
  def _reduce_73(val, _values, result)
                             kwargs = val[0]
                         @tree << GoalLine.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 321)
  def _reduce_74(val, _values, result)
      result = { goals1: val[0],
                                                              goals2: [] } 

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 324)
  def _reduce_75(val, _values, result)
      result = { goals1: [],
                                                              goals2: val[2] } 

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 327)
  def _reduce_76(val, _values, result)
      result = { goals1: val[0],
                                                              goals2: val[2] }

    result
  end
.,.,

# reduce 77 omitted

# reduce 78 omitted

module_eval(<<'.,.,', 'parser.y', 341)
  def _reduce_79(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 342)
  def _reduce_80(val, _values, result)
     result.push( val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 356)
  def _reduce_81(val, _values, result)
                      result = Goal.new( player:  val[0],
                                     minutes: val[1] )   

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 368)
  def _reduce_82(val, _values, result)
     result = val
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 369)
  def _reduce_83(val, _values, result)
     result.push( val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 370)
  def _reduce_84(val, _values, result)
     result.push( val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 376)
  def _reduce_85(val, _values, result)
                            kwargs = {}.merge( val[0][1] )
                        result = Minute.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 381)
  def _reduce_86(val, _values, result)
                            kwargs = { }.merge( val[0][1] ).merge( val[1] )
                        result = Minute.new( **kwargs )

    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 385)
  def _reduce_87(val, _values, result)
      result = { og: true }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 386)
  def _reduce_88(val, _values, result)
      result = { pen: true }
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 391)
  def _reduce_89(val, _values, result)
     puts '  MATCH empty_line'
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class RaccMatchParser
