require 'hoe'
require './lib/sportdb/search/version.rb'

Hoe.spec 'sportdb-search' do

  self.version = SportDb::Module::Search::VERSION

  self.summary = "sportdb-search - find national teams, clubs, leagues & more"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['sportdb-catalogs',   '>= 1.2.3'],
  ]

  self.spec_extras = {
   required_ruby_version: '>= 3.1.0'
  }
end
