require 'hoe'
require './lib/sportdb/quick/version.rb'


Hoe.spec 'sportdb-quick' do

  self.version = SportDb::Module::Quick::VERSION

  self.summary = "sportdb-quick - football.txt (quick) match readers and more"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email  = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
       ['sportdb-parser',  '>= 0.5.4'],
       ['sportdb-structs', '>= 0.5.0'],
       ['logutils',        '>= 0.6.1'],
  ]

  self.spec_extras = {
    required_ruby_version: '>= 3.1.0'
  }
end
