require 'hoe'
require './lib/sportdb/match/formats/version.rb'

Hoe.spec 'sportdb-match-formats' do

  self.version = SportDb::MatchFormats::VERSION

  self.summary = "sportdb-formats - sport.db match format reader and parser"
  self.description = summary

  self.urls = ['https://github.com/sportdb/sport.db']

  self.author = 'Gerald Bauer'
  self.email = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['sportdb-formats', '>= 0.4.0'],
  ]

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }
end
