require 'hoe'
require './lib/racingdb/version.rb'

Hoe.spec 'racingdb' do

  self.version = RacingDb::VERSION

  self.summary = 'racingdb - sport.db addon for racing (e.g. formula 1, tour de france, ski racing, marathons, etc.)'
  self.description = summary

  self.urls = ['https://github.com/sportdb/sport.db']

  self.author = 'Gerald Bauer'
  self.email = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.spec_extras = {
   :required_ruby_version => '>= 1.9.2'
  }

end
