require 'hoe'
require './lib/sportdb/teams/version.rb'

Hoe.spec 'sportdb-teams' do

  self.version = SportDb::Teams::VERSION

  self.summary = "sportdb-teams - sport.db clubs and national teams reader and quick starter zero-config lookup index"
  self.description = summary

  self.urls = ['https://github.com/sportdb/sport.db']

  self.author = 'Gerald Bauer'
  self.email = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['sportdb-countries', '>= 0.5.1'],
    ##  ['sportdb-leagues',   '>= 0.2.2'],  -- todo/check: add leagues - why? why not?
  ]

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }

end
