require 'hoe'
require './lib/sportdb/sync/version.rb'

Hoe.spec 'sportdb-sync' do

  self.version = SportDb::Module::Sync::VERSION

  self.summary = "sportdb-sync - sport.db sync helpers for leagues, seasons, clubs, match schedules and results, and more"
  self.description = summary

  self.urls = ['https://github.com/sportdb/sport.db']

  self.author = 'Gerald Bauer'
  self.email  = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['sportdb-catalogs',  '>= 1.0.0'],
    ['sportdb-models',    '>= 2.0.2'],
  ]

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }
end
