require 'hoe'
require './lib/sportdb/formats/version.rb'

Hoe.spec 'sportdb-formats' do

  self.version = SportDb::Module::Formats::VERSION

  self.summary = "sportdb-formats - sport.db format and text utilities"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['sportdb-search',   '>= 0.0.1'],
    ['sportdb-quick',    '>= 0.2.0'],
    ['rubyzip',          '>= 2.3.2' ],
  ]

  self.spec_extras = {
    required_ruby_version: '>= 3.1.0'
  }
end
