require 'hoe'
require './lib/sportdb/formats/version.rb'

Hoe.spec 'sportdb-formats' do

  self.version = SportDb::Formats::VERSION

  self.summary = "sportdb-formats - sport.db format and text utilities"
  self.description = summary

  self.urls = ['https://github.com/sportdb/sport.db']

  self.author = 'Gerald Bauer'
  self.email = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['alphabets',   '>= 0.1.0'],
    ['csvreader',   '>= 1.2.4'],
    ['textutils',   '>= 1.4.0'],
  ]

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
