require 'hoe'
require './lib/fifa/version.rb'

Hoe.spec 'fifa' do

  self.version = Fifa::VERSION

  self.summary = "fifa - the world's football countries and codes (incl. non-member countries and irregular codes)"
  self.description = summary

  self.urls = ['https://github.com/sportdb/sport.db']

  self.author = 'Gerald Bauer'
  self.email = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['sportdb-countries',   '>= 0.2.0'],
  ]

  self.spec_extras = {
   :required_ruby_version => '>= 2.2.2'
  }

end
