#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'
class MatchParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
     9,    11,     6,    12,     8,     7,     6,    13,     8,     7,
    14,    15 ]

racc_action_check = [
     1,     6,     1,     7,     1,     1,     0,     9,     0,     0,
    11,    12 ]

racc_action_pointer = [
     4,     0,   nil,   nil,   nil,   nil,    -2,     0,   nil,     7,
   nil,     6,     7,   nil,   nil,   nil ]

racc_action_default = [
    -9,    -9,    -1,    -3,    -4,    -5,    -9,    -9,    -8,    -9,
    -2,    -9,    -9,    16,    -6,    -7 ]

racc_goto_table = [
     2,    10,     1 ]

racc_goto_check = [
     2,     2,     1 ]

racc_goto_pointer = [
   nil,     2,     0,   nil,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 7, :_reduce_none,
  2, 7, :_reduce_none,
  1, 8, :_reduce_none,
  1, 8, :_reduce_none,
  1, 8, :_reduce_none,
  3, 9, :_reduce_6,
  3, 10, :_reduce_7,
  1, 11, :_reduce_8 ]

racc_reduce_n = 9

racc_shift_n = 16

racc_token_table = {
  false => 0,
  :error => 1,
  "Oct" => 2,
  :NUMBER => 3,
  :NEWLINE => 4,
  :TEXT => 5 }

racc_nt_base = 6

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"Oct\"",
  "NUMBER",
  "NEWLINE",
  "TEXT",
  "$start",
  "statements",
  "statement",
  "date_line",
  "team_line",
  "empty_line" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

module_eval(<<'.,.,', 'parser.y', 24)
  def _reduce_6(val, _values, result)
     puts '  MATCH date line'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 28)
  def _reduce_7(val, _values, result)
     puts '  MATCH team_line'
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_8(val, _values, result)
     puts '  MATCH empty_line'
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class MatchParser
