require 'hoe'
require './lib/sportdb/service/version.rb'

Hoe.spec 'sportdb-service' do

  self.version = SportDb::Service::VERSION

  self.summary = 'sportdb-service - sport.db addon for web service (HTTP JSON API)'
  self.description = summary

  self.urls = ['https://github.com/sportdb/sport.db']

  self.author = 'Gerald Bauer'
  self.email  = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
