#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'
class MatchParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    48,    77,    35,    21,    42,    10,    19,    20,    19,    11,
    12,    18,    13,    47,    16,    28,    28,    18,    10,    33,
    20,    19,    11,    12,    39,    13,    39,    16,    51,    34,
    18,    26,    40,    28,    40,    44,    45,    46,    29,    30,
    31,    32,    58,    59,    70,    71,    72,    73,    54,    56,
    60,    63,    34,    64,    28,    28,    67,    54,    74,    75,
    76,    78,    28 ]

racc_action_check = [
    24,    66,    13,     1,    16,     1,    14,     1,     1,     1,
     1,    16,     1,    21,     1,    24,    66,     1,     0,    12,
     0,     0,     0,     0,    15,     0,    36,     0,    25,    12,
     0,     8,    15,     8,    36,    19,    19,    19,    10,    10,
    11,    11,    31,    31,    54,    54,    55,    55,    28,    29,
    35,    40,    42,    43,    48,    50,    51,    52,    57,    60,
    62,    76,    77 ]

racc_action_pointer = [
    16,     3,   nil,   nil,   nil,   nil,   nil,   nil,    14,   nil,
    35,    37,    15,    -5,     1,    20,    -3,   nil,   nil,    20,
   nil,    13,   nil,   nil,    -4,    10,   nil,   nil,    28,    44,
   nil,    35,   nil,   nil,   nil,    40,    22,   nil,   nil,   nil,
    46,   nil,    38,    48,   nil,   nil,   nil,   nil,    35,   nil,
    36,    52,    37,   nil,    23,    42,   nil,    54,   nil,   nil,
    55,   nil,    47,   nil,   nil,   nil,    -3,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    56,    43,   nil ]

racc_action_default = [
   -54,   -54,    -1,    -3,    -4,    -5,    -6,    -7,   -54,    -9,
   -54,   -54,   -30,   -54,   -54,   -54,   -22,   -24,   -32,   -54,
   -53,   -54,    -2,    -8,   -42,   -54,   -41,   -43,   -54,   -54,
   -18,   -54,   -19,   -16,   -31,   -54,   -54,   -21,   -25,   -26,
   -54,   -23,   -30,   -54,   -34,   -35,   -36,    79,   -37,   -45,
   -54,   -39,   -46,   -47,   -49,   -54,   -11,   -54,   -14,   -15,
   -54,   -20,   -27,   -28,   -33,   -44,   -54,   -40,   -48,   -50,
   -51,   -52,   -10,   -12,   -13,   -17,   -54,   -38,   -29 ]

racc_goto_table = [
    49,    24,    53,     1,    37,     2,    22,    23,    55,    57,
    36,    41,    62,    43,    25,    50,    52,    69,   nil,   nil,
   nil,   nil,   nil,   nil,    65,    61,    68,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    49,    66,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    65 ]

racc_goto_check = [
    23,    20,    25,     1,    15,     2,     2,     9,    11,    12,
    14,    16,    18,    19,    21,    22,    24,    26,   nil,   nil,
   nil,   nil,   nil,   nil,    23,    15,    25,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    23,    20,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    23 ]

racc_goto_pointer = [
   nil,     3,     5,   nil,   nil,   nil,   nil,   nil,   nil,    -1,
   nil,   -21,   -22,   nil,    -4,   -11,    -5,   nil,   -28,    -6,
    -7,     6,   -10,   -24,   -12,   -26,   -37 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,     6,     7,     8,   nil,
     9,   nil,   nil,    14,    15,   nil,    17,    38,   nil,   nil,
   nil,   nil,   nil,    27,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 24, :_reduce_none,
  2, 24, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  1, 25, :_reduce_none,
  2, 25, :_reduce_none,
  1, 25, :_reduce_none,
  4, 29, :_reduce_none,
  1, 34, :_reduce_none,
  2, 34, :_reduce_none,
  4, 30, :_reduce_none,
  1, 35, :_reduce_none,
  1, 35, :_reduce_none,
  2, 26, :_reduce_none,
  4, 26, :_reduce_17,
  2, 27, :_reduce_none,
  2, 28, :_reduce_none,
  3, 31, :_reduce_none,
  2, 31, :_reduce_21,
  1, 36, :_reduce_none,
  2, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 38, :_reduce_none,
  1, 38, :_reduce_none,
  2, 40, :_reduce_none,
  1, 41, :_reduce_none,
  3, 41, :_reduce_none,
  1, 39, :_reduce_none,
  2, 39, :_reduce_none,
  1, 39, :_reduce_none,
  3, 37, :_reduce_none,
  1, 42, :_reduce_none,
  1, 42, :_reduce_none,
  1, 42, :_reduce_none,
  2, 32, :_reduce_none,
  4, 32, :_reduce_none,
  1, 45, :_reduce_none,
  2, 45, :_reduce_none,
  1, 44, :_reduce_none,
  1, 44, :_reduce_none,
  1, 43, :_reduce_none,
  3, 43, :_reduce_none,
  2, 43, :_reduce_none,
  2, 46, :_reduce_none,
  1, 47, :_reduce_none,
  2, 47, :_reduce_none,
  1, 48, :_reduce_none,
  2, 48, :_reduce_none,
  1, 49, :_reduce_none,
  1, 49, :_reduce_none,
  1, 33, :_reduce_53 ]

racc_reduce_n = 54

racc_shift_n = 79

racc_token_table = {
  false => 0,
  :error => 1,
  :GROUP => 2,
  "|" => 3,
  :NEWLINE => 4,
  :TEXT => 5,
  :ROUND => 6,
  :DATE => 7,
  :DURATION => 8,
  "[" => 9,
  "]" => 10,
  :ORD => 11,
  "@" => 12,
  "," => 13,
  :TIME => 14,
  :SCORE => 15,
  :VS => 16,
  "-" => 17,
  ";" => 18,
  :PLAYER => 19,
  :MINUTE => 20,
  :OG => 21,
  :PEN => 22 }

racc_nt_base = 23

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "GROUP",
  "\"|\"",
  "NEWLINE",
  "TEXT",
  "ROUND",
  "DATE",
  "DURATION",
  "\"[\"",
  "\"]\"",
  "ORD",
  "\"@\"",
  "\",\"",
  "TIME",
  "SCORE",
  "VS",
  "\"-\"",
  "\";\"",
  "PLAYER",
  "MINUTE",
  "OG",
  "PEN",
  "$start",
  "statements",
  "statement",
  "date_header",
  "group_header",
  "round_header",
  "group_def",
  "round_def",
  "match_line",
  "goal_lines",
  "empty_line",
  "team_values",
  "round_date_opts",
  "match_opts",
  "match",
  "more_match_opts",
  "date_opts",
  "geo_opts",
  "geo_values",
  "score_value",
  "goals",
  "goal_opts",
  "goal_sep",
  "goal",
  "minutes",
  "minute",
  "minute_opts" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

module_eval(<<'.,.,', 'parser.y', 43)
  def _reduce_17(val, _values, result)
     puts '  MATCH date line'
    result
  end
.,.,

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

module_eval(<<'.,.,', 'parser.y', 54)
  def _reduce_21(val, _values, result)
     puts '  MATCH team_line'
    result
  end
.,.,

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

module_eval(<<'.,.,', 'parser.y', 115)
  def _reduce_53(val, _values, result)
     puts '  MATCH empty_line'
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class MatchParser
