#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'
class MatchParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    27,    32,    11,    76,    26,    21,    12,    13,    31,    14,
    55,    24,    33,    18,    11,    20,    26,    21,    12,    13,
    36,    14,    45,    24,    45,    18,    42,    20,    37,    48,
    29,    30,    46,    58,    46,    39,    40,    20,    52,    36,
    56,    34,    52,    50,    51,    24,    55,    50,    51,    65,
    66,    78,    79,    83,    84,    60,    61,    63,    67,    68,
    55,    69,    71,    73,    33,    74,    36,    81,    36,    85,
    86,    87,    88,    55,    36,    36,    90 ]

racc_action_check = [
     1,    13,     1,    53,     1,     1,     1,     1,    12,     1,
    53,     1,    13,     1,     0,     1,     0,     0,     0,     0,
    23,     0,    17,     0,    41,     0,    16,     0,    15,    18,
    11,    11,    17,    23,    41,    15,    15,    18,    21,    14,
    22,    14,    42,    21,    21,    14,    21,    42,    42,    31,
    31,    55,    55,    62,    62,    24,    27,    29,    34,    35,
    36,    38,    44,    46,    48,    49,    57,    58,    60,    64,
    67,    68,    72,    76,    80,    82,    88 ]

racc_action_pointer = [
    12,     0,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    27,     5,    -3,    34,    24,    21,    18,    22,   nil,
   nil,    27,    36,    15,    37,   nil,   nil,    56,   nil,    52,
   nil,    42,   nil,   nil,    48,    49,    41,   nil,    55,   nil,
   nil,    20,    31,   nil,    58,   nil,    58,   nil,    49,    60,
   nil,   nil,   nil,    -9,   nil,    31,   nil,    61,    63,   nil,
    63,   nil,    49,   nil,    65,   nil,   nil,    66,    67,   nil,
   nil,   nil,    60,   nil,   nil,   nil,    54,   nil,   nil,   nil,
    69,   nil,    70,   nil,   nil,   nil,   nil,   nil,    71,   nil,
   nil ]

racc_action_default = [
   -60,   -60,    -1,    -3,    -4,    -5,    -6,    -7,    -8,    -9,
   -10,   -60,   -21,   -35,   -60,   -60,   -60,   -60,   -27,   -29,
   -37,   -60,   -60,   -44,   -60,   -49,   -59,   -60,    -2,   -60,
   -19,   -60,   -17,   -36,   -60,   -60,   -60,   -20,   -60,   -23,
   -24,   -60,   -60,   -26,   -60,   -31,   -60,   -28,   -35,   -60,
   -39,   -40,   -41,   -51,   -52,   -55,   -43,   -60,   -47,   -50,
   -60,    91,   -60,   -12,   -60,   -15,   -16,   -60,   -60,   -22,
   -25,   -30,   -32,   -33,   -38,   -53,   -60,   -56,   -57,   -58,
   -46,   -48,   -45,   -11,   -13,   -14,   -18,   -42,   -60,   -54,
   -34 ]

racc_goto_table = [
    59,    43,    80,    75,     1,    82,     2,    28,    62,    64,
    38,    41,    47,    72,    35,    57,    77,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    70,    89,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    59,   nil,    59 ]

racc_goto_check = [
    25,    17,    23,    27,     1,    23,     2,     2,    11,    12,
    14,    16,    18,    20,    22,    24,    28,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    17,    27,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    25,   nil,    25 ]

racc_goto_pointer = [
   nil,     4,     6,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   -21,   -22,   nil,    -5,   nil,    -5,   -16,    -6,   nil,
   -33,   nil,     0,   -55,    -8,   -23,   nil,   -50,   -39 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,     6,     7,     8,     9,
    10,   nil,   nil,    15,   nil,    16,    17,   nil,    19,    44,
   nil,    49,    22,    23,   nil,    25,    53,    54,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 23, :_reduce_none,
  2, 23, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  1, 24, :_reduce_none,
  4, 28, :_reduce_none,
  1, 33, :_reduce_none,
  2, 33, :_reduce_none,
  4, 29, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  2, 25, :_reduce_none,
  4, 25, :_reduce_18,
  2, 26, :_reduce_none,
  2, 27, :_reduce_none,
  1, 35, :_reduce_none,
  3, 35, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  3, 30, :_reduce_none,
  2, 30, :_reduce_26,
  1, 37, :_reduce_none,
  2, 37, :_reduce_none,
  1, 37, :_reduce_none,
  2, 39, :_reduce_none,
  1, 39, :_reduce_none,
  2, 41, :_reduce_none,
  1, 42, :_reduce_none,
  3, 42, :_reduce_none,
  1, 40, :_reduce_none,
  2, 40, :_reduce_none,
  1, 40, :_reduce_none,
  3, 38, :_reduce_none,
  1, 43, :_reduce_none,
  1, 43, :_reduce_none,
  1, 43, :_reduce_none,
  4, 31, :_reduce_none,
  2, 31, :_reduce_none,
  1, 44, :_reduce_none,
  3, 44, :_reduce_none,
  3, 44, :_reduce_none,
  1, 46, :_reduce_none,
  2, 46, :_reduce_none,
  1, 45, :_reduce_none,
  2, 45, :_reduce_none,
  2, 47, :_reduce_51,
  1, 48, :_reduce_none,
  2, 48, :_reduce_none,
  3, 48, :_reduce_none,
  1, 49, :_reduce_none,
  2, 49, :_reduce_none,
  1, 50, :_reduce_none,
  1, 50, :_reduce_none,
  1, 32, :_reduce_59 ]

racc_reduce_n = 60

racc_shift_n = 91

racc_token_table = {
  false => 0,
  :error => 1,
  :GROUP => 2,
  "|" => 3,
  :NEWLINE => 4,
  :TEXT => 5,
  :ROUND => 6,
  :DATE => 7,
  :DURATION => 8,
  "[" => 9,
  "]" => 10,
  "-" => 11,
  "," => 12,
  :ORD => 13,
  "@" => 14,
  :TIME => 15,
  :SCORE => 16,
  :VS => 17,
  ";" => 18,
  :MINUTE => 19,
  :OG => 20,
  :PEN => 21 }

racc_nt_base = 22

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "GROUP",
  "\"|\"",
  "NEWLINE",
  "TEXT",
  "ROUND",
  "DATE",
  "DURATION",
  "\"[\"",
  "\"]\"",
  "\"-\"",
  "\",\"",
  "ORD",
  "\"@\"",
  "TIME",
  "SCORE",
  "VS",
  "\";\"",
  "MINUTE",
  "OG",
  "PEN",
  "$start",
  "statements",
  "statement",
  "date_header",
  "group_header",
  "round_header",
  "group_def",
  "round_def",
  "match_line",
  "goal_lines",
  "empty_line",
  "team_values",
  "round_date_opts",
  "round_values",
  "round_sep",
  "match_opts",
  "match",
  "more_match_opts",
  "date_opts",
  "geo_opts",
  "geo_values",
  "score_value",
  "goal_lines_body",
  "goals",
  "goal_sep",
  "goal",
  "minutes",
  "minute",
  "minute_opts" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

module_eval(<<'.,.,', 'parser.y', 44)
  def _reduce_18(val, _values, result)
     puts '  MATCH date line'
    result
  end
.,.,

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

module_eval(<<'.,.,', 'parser.y', 64)
  def _reduce_26(val, _values, result)
     puts '  MATCH team_line'
    result
  end
.,.,

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

module_eval(<<'.,.,', 'parser.y', 130)
  def _reduce_51(val, _values, result)
     puts '  MATCH goal (player w/ minutes)'
    result
  end
.,.,

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

module_eval(<<'.,.,', 'parser.y', 144)
  def _reduce_59(val, _values, result)
     puts '  MATCH empty_line'
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class MatchParser
