require 'hoe'
require './lib/footballdb/version.rb'

Hoe.spec 'footballdb' do

  self.version = FootballDb::VERSION

  self.summary = 'footballdb - sport.db addon for football stats n more'
  self.description = summary

  self.urls = ['https://github.com/sportdb/football.db.ruby']

  ## note: does not work - no authors defined? only author
  ## self.authors = [ 'Carl Svensson', 'Gerald Bauer' ]
  ## self.email = 'opensport@googlegroups.com'

  developer 'Carl Svensson', 'opensport@googlegroups.com'
  developer 'Gerald Bauer',  'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.spec_extras = {
   :required_ruby_version => '>= 1.9.2'
  }
end
