require 'hoe'


Hoe.spec 'fbtxt' do
  self.version = '0.1.2'

  self.summary = "fbtxt - convert football match schedules & more in tabular comma-separated values (csv) format to (future-proof & evergreen) football.txt"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email  = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
       ['sportdb-writers', '>= 0.4.0'],
  ]

  self.spec_extras = {
    required_ruby_version: '>= 3.1.0'
  }
end
