require 'hoe'
require './lib/sportdb/parser/version.rb'


Hoe.spec 'sportdb-parser' do

  self.version = SportDb::Module::Parser::VERSION

  self.summary = "sportdb-parser - football.txt match parser (& tokenizer)"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
       ['cocos', '>= 0.4.0'],
       ['racc'],   ## maybe inline runtime later if possible - why? why not?
  ]

  self.spec_extras = {
    required_ruby_version: '>= 3.1.0'
  }
end
