require 'hoe'
require './lib/sportdb/countries/version.rb'

Hoe.spec 'sportdb-countries' do

  self.version = SportDb::Countries::VERSION

  self.summary = "sportdb-countries - sport.db countries of the world reader and zero-config quick starter settings"
  self.description = summary

  self.urls = ['https://github.com/sportdb/sport.db']

  self.author = 'Gerald Bauer'
  self.email = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file = 'README.md'
  self.history_file = 'HISTORY.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['csvreader',   '>= 1.2.4'],
  ]

  self.spec_extras = {
   :required_ruby_version => '>= 2.2.2'
  }

end
