require 'hoe'
require './lib/sportdb/catalogs/version.rb'

Hoe.spec 'sportdb-catalogs' do

  self.version = SportDb::Module::Catalogs::VERSION

  self.summary = "sportdb-catalogs - sport.db (search 'n' find) catalogs for countries, leagues, clubs, national teams, and more"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email  = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['sportdb-structs', '>= 0.5.0'],
    ['footballdb-data', '>= 2025.1.3'],   ## add builtin default db
    ['sqlite3'],          ## add sqlite for "metal" use (no activerecord etc.)
  ]

  self.spec_extras = {
   required_ruby_version: '>= 3.1.0'
  }

end
