require 'hoe'
require './lib/sportdb/catalogs/version.rb'

Hoe.spec 'sportdb-catalogs' do

  self.version = SportDb::Module::Catalogs::VERSION

  self.summary = "sportdb-catalogs - sport.db (search 'n' find) catalogs for countries, leagues, clubs, national teams, and more"
  self.description = summary

  self.urls = ['https://github.com/sportdb/sport.db']

  self.author = 'Gerald Bauer'
  self.email  = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['sportdb-formats',    '>= 1.1.0'],
    ## dataset libs / gems
    ['fifa',               '>= 2020.5.18'],    ## for (builtin/default) countries
    ['footballdb-clubs',   '>= 2020.6.16'],    ## for (builtin/default) clubs
    ['footballdb-leagues', '>= 2020.6.16'],    ## for (builtin/default) leagues & cups
  ]

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
