require 'hoe'
require './lib/sports/version.rb'

Hoe.spec 'sports' do

  self.version = SportDb::Module::Sports::VERSION

  self.summary = "sports - sport data structures for matches, scores, leagues, seasons, rounds, groups, teams, clubs and more"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['sportdb-structs', '>= 0.5.0'],
  ]

  self.spec_extras = {
    required_ruby_version: '>= 3.1.0'
  }
end
