require 'hoe'
require './lib/sportdb/models_v2/version.rb'


Hoe.spec 'sportdb-models_v2' do

  self.version = SportDbV2::Module::Models::VERSION

  self.summary = "sportdb-models_v2 - sport.db schema 'n' models for easy (re)use"
  self.description = summary

  self.urls    = { home: 'https://github.com/sportdb/sport.db' }

  self.author  = 'Gerald Bauer'
  self.email   = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  #  -- NB: auto-changed when included in manifest
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.extra_deps = [
    ['cocos'],
    ## add props & logutils (or props/logutils-activerecord good enough?) - why? why not? 
    ['props-activerecord'],    ## pulls in activerecord
    ['logutils-activerecord'],
    ['sportdb-quick'],
  ]

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 3.1.0'
  }
end
