require 'hoe'
require './lib/sportdb/langs/version.rb'

Hoe.spec 'sportdb-langs' do

  self.version = SportDb::Langs::VERSION

  self.summary = "sportdb-langs - sport.db language utilities"
  self.description = summary

  self.urls = ['https://github.com/sportdb/sport.db']

  self.author = 'Gerald Bauer'
  self.email = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['logutils',   '>= 0.6.1'],
  ]

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
