#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'
class MarkdownParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
     8,     3,     9,    10,    11,    13,    14,    13,    16,    17,
    18,    19 ]

racc_action_check = [
     2,     1,     2,     2,     2,     2,     3,     7,     8,     9,
    10,    13 ]

racc_action_pointer = [
   nil,     1,    -2,     6,   nil,   nil,   nil,     0,     5,     6,
     7,   nil,   nil,     5,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_action_default = [
    -2,   -14,    -1,   -14,    -3,    -4,    -5,    -6,   -14,   -14,
   -14,   -10,   -11,   -14,    20,   -12,    -7,    -8,    -9,   -13 ]

racc_goto_table = [
    12,     1,     2,     4,     5,    15,     6,     7 ]

racc_goto_check = [
     7,     1,     2,     3,     4,     7,     5,     6 ]

racc_goto_pointer = [
   nil,     1,     2,     1,     2,     4,     5,    -2 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 9, :_reduce_none,
  0, 10, :_reduce_none,
  2, 10, :_reduce_none,
  1, 11, :_reduce_none,
  1, 11, :_reduce_none,
  1, 11, :_reduce_none,
  2, 12, :_reduce_none,
  2, 12, :_reduce_none,
  2, 12, :_reduce_none,
  1, 13, :_reduce_none,
  1, 14, :_reduce_none,
  2, 14, :_reduce_none,
  2, 15, :_reduce_none ]

racc_reduce_n = 14

racc_shift_n = 20

racc_token_table = {
  false => 0,
  :error => 1,
  "#" => 2,
  :text => 3,
  "##" => 4,
  "###" => 5,
  :TEXT => 6,
  "-" => 7 }

racc_nt_base = 8

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"#\"",
  "text",
  "\"##\"",
  "\"###\"",
  "TEXT",
  "\"-\"",
  "$start",
  "document",
  "element_list",
  "element",
  "header",
  "paragraph",
  "list",
  "list_item" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class MarkdownParser
