require 'hoe'


Hoe.spec 'fbtxt2json' do
  self.version = '0.1.0'

  self.summary = "fbtxt2json - convert football.txt match schedules & more to json"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email  = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
       ['sportdb-quick', '>= 0.2.1'],
  ]

  self.spec_extras = {
    required_ruby_version: '>= 3.1.0'
  }
end
