require 'hoe'
require './lib/alphabets/version.rb'

Hoe.spec 'alphabets' do

  self.version = Alphabet::VERSION

  self.summary = "alphabets - "
  self.description = summary

  self.urls = ['https://github.com/sportdb/sport.db']

  self.author = 'Gerald Bauer'
  self.email = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = []

  self.spec_extras = {
   :required_ruby_version => '>= 2.2.2'
  }

end
