require 'hoe'
require './lib/score-formats/version.rb'

Hoe.spec 'score-formats' do

  self.version = ScoreFormats::VERSION

  self.summary = "score-formats - read / parse and print sports match scores (incl. half time, full time, extra time, penalties and more)"
  self.description = summary

  self.urls = { home: 'https://github.com/sportdb/sport.db' }

  self.author = 'Gerald Bauer'
  self.email = 'gerald.bauer@gmail.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = []

  self.spec_extras = {
    required_ruby_version: '>= 3.1.0'
  }
end
