require 'hoe'
require './lib/sportdb/config/version.rb'

Hoe.spec 'sportdb-config' do

  self.version = SportDb::Boot::VERSION

  self.summary = "sportdb-config - sport.db configuration settings and built-in defaults"
  self.description = summary

  self.urls = ['https://github.com/sportdb/sport.db']

  self.author = 'Gerald Bauer'
  self.email  = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['sportdb-formats',    '>= 1.0.5'],
    ## dataset libs / gems
    ['fifa',               '>= 2020.5.18'],    ## for (builtin/default) countries
    ['footballdb-clubs',   '>= 2020.5.10'],    ## for (builtin/default) clubs
    ['footballdb-leagues', '>= 2020.5.10'],    ## for (builtin/default) leagues & cups
  ]

  self.spec_extras = {
   required_ruby_version: '>= 2.2.2'
  }

end
