require 'hoe'
require './lib/sportdb/importers/version.rb'

Hoe.spec 'sportdb-importers' do

  self.version = SportDb::Module::Importers::VERSION

  self.summary = "sportdb-importers - tools 'n' scripts for importing sports (football) data in alternate (text) formats incl. comma-separated values (csv) format"
  self.description = summary

  self.urls = ['https://github.com/sportdb/sport.db']

  self.author = 'Gerald Bauer'
  self.email  = 'opensport@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.extra_deps = [
    ['sportdb-sync', '>= 1.0.0'],
  ]

  self.spec_extras = {
    required_ruby_version: '>= 2.2.2'
  }

end
